// <auto-generated />
using System;
using CondoBox.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondoBox.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("CondoBox.Domain.EmailSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CryptoPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailCC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSend");
                });

            modelBuilder.Entity("CondoBox.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CondoBox.Domain.Mail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeRegister")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("CondoBox.Domain.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("CondoBox.Domain.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apt = "01",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 2,
                            Apt = "02",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 3,
                            Apt = "03",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 4,
                            Apt = "04",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 5,
                            Apt = "05",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 6,
                            Apt = "11",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 7,
                            Apt = "12",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 8,
                            Apt = "13",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 9,
                            Apt = "14",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 10,
                            Apt = "15",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 11,
                            Apt = "16",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 12,
                            Apt = "21",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 13,
                            Apt = "22",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 14,
                            Apt = "23",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 15,
                            Apt = "24",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 16,
                            Apt = "25",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 17,
                            Apt = "26",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 18,
                            Apt = "31",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 19,
                            Apt = "32",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 20,
                            Apt = "33",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 21,
                            Apt = "34",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 22,
                            Apt = "35",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 23,
                            Apt = "36",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 24,
                            Apt = "41",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 25,
                            Apt = "42",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 26,
                            Apt = "43",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 27,
                            Apt = "44",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 28,
                            Apt = "45",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 29,
                            Apt = "46",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 30,
                            Apt = "51",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 31,
                            Apt = "52",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 32,
                            Apt = "53",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 33,
                            Apt = "54",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 34,
                            Apt = "55",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 35,
                            Apt = "56",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 36,
                            Apt = "61",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 37,
                            Apt = "62",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 38,
                            Apt = "63",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 39,
                            Apt = "64",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 40,
                            Apt = "65",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 41,
                            Apt = "66",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 42,
                            Apt = "71",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 43,
                            Apt = "72",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 44,
                            Apt = "73",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 45,
                            Apt = "74",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 46,
                            Apt = "75",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 47,
                            Apt = "76",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 48,
                            Apt = "81",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 49,
                            Apt = "82",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 50,
                            Apt = "83",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 51,
                            Apt = "84",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 52,
                            Apt = "85",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 53,
                            Apt = "86",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 54,
                            Apt = "91",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 55,
                            Apt = "92",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 56,
                            Apt = "93",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 57,
                            Apt = "94",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 58,
                            Apt = "95",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 59,
                            Apt = "96",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 60,
                            Apt = "101",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 61,
                            Apt = "102",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 62,
                            Apt = "103",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 63,
                            Apt = "104",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 64,
                            Apt = "105",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 65,
                            Apt = "106",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 66,
                            Apt = "111",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 67,
                            Apt = "112",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 68,
                            Apt = "113",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 69,
                            Apt = "114",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 70,
                            Apt = "115",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 71,
                            Apt = "116",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 72,
                            Apt = "121",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 73,
                            Apt = "122",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 74,
                            Apt = "123",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 75,
                            Apt = "124",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 76,
                            Apt = "125",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 77,
                            Apt = "126",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 78,
                            Apt = "131",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 79,
                            Apt = "132",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 80,
                            Apt = "133",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 81,
                            Apt = "134",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 82,
                            Apt = "135",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 83,
                            Apt = "136",
                            Building = "BLOCO I"
                        },
                        new
                        {
                            Id = 84,
                            Apt = "01",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 85,
                            Apt = "02",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 86,
                            Apt = "03",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 87,
                            Apt = "04",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 88,
                            Apt = "05",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 89,
                            Apt = "11",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 90,
                            Apt = "12",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 91,
                            Apt = "13",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 92,
                            Apt = "14",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 93,
                            Apt = "15",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 94,
                            Apt = "16",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 95,
                            Apt = "21",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 96,
                            Apt = "22",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 97,
                            Apt = "23",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 98,
                            Apt = "24",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 99,
                            Apt = "25",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 100,
                            Apt = "26",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 101,
                            Apt = "31",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 102,
                            Apt = "32",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 103,
                            Apt = "33",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 104,
                            Apt = "34",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 105,
                            Apt = "35",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 106,
                            Apt = "36",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 107,
                            Apt = "41",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 108,
                            Apt = "42",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 109,
                            Apt = "43",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 110,
                            Apt = "44",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 111,
                            Apt = "45",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 112,
                            Apt = "46",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 113,
                            Apt = "51",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 114,
                            Apt = "52",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 115,
                            Apt = "53",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 116,
                            Apt = "54",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 117,
                            Apt = "55",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 118,
                            Apt = "56",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 119,
                            Apt = "61",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 120,
                            Apt = "62",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 121,
                            Apt = "63",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 122,
                            Apt = "64",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 123,
                            Apt = "65",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 124,
                            Apt = "66",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 125,
                            Apt = "71",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 126,
                            Apt = "72",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 127,
                            Apt = "73",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 128,
                            Apt = "74",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 129,
                            Apt = "75",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 130,
                            Apt = "76",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 131,
                            Apt = "81",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 132,
                            Apt = "82",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 133,
                            Apt = "83",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 134,
                            Apt = "84",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 135,
                            Apt = "85",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 136,
                            Apt = "86",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 137,
                            Apt = "91",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 138,
                            Apt = "92",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 139,
                            Apt = "93",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 140,
                            Apt = "94",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 141,
                            Apt = "95",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 142,
                            Apt = "96",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 143,
                            Apt = "101",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 144,
                            Apt = "102",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 145,
                            Apt = "103",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 146,
                            Apt = "104",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 147,
                            Apt = "105",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 148,
                            Apt = "106",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 149,
                            Apt = "111",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 150,
                            Apt = "112",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 151,
                            Apt = "113",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 152,
                            Apt = "114",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 153,
                            Apt = "115",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 154,
                            Apt = "116",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 155,
                            Apt = "121",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 156,
                            Apt = "122",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 157,
                            Apt = "123",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 158,
                            Apt = "124",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 159,
                            Apt = "125",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 160,
                            Apt = "126",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 161,
                            Apt = "131",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 162,
                            Apt = "132",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 163,
                            Apt = "133",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 164,
                            Apt = "134",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 165,
                            Apt = "135",
                            Building = "BLOCO II"
                        },
                        new
                        {
                            Id = 166,
                            Apt = "136",
                            Building = "BLOCO II"
                        });
                });

            modelBuilder.Entity("CondoBox.Domain.Mail", b =>
                {
                    b.HasOne("CondoBox.Domain.Unit", "Unit")
                        .WithMany("Mails")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CondoBox.Domain.Resident", b =>
                {
                    b.HasOne("CondoBox.Domain.Unit", "Unit")
                        .WithMany("Residents")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("CondoBox.Domain.Unit", b =>
                {
                    b.Navigation("Mails");

                    b.Navigation("Residents");
                });
#pragma warning restore 612, 618
        }
    }
}
